version: "3.8"

services:
  omni-endpoint:
    build: .
    container_name: omni-endpoint
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
    extra_hosts:
      - "starserver:host-gateway"
