version: "3.8"

services:
  omni-endpoint:
    build: .
    container_name: omni-endpoint
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /home/celestialpawz/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
    extra_hosts:
      - "starserver:host-gateway"
